(defproject timezones "0.2.0-SNAPSHOT"
  :main timezones
  :aot [timezones]
  :dependencies [[org.clojure/clojure "1.10.0"]
                 [enlive/enlive "1.1.6"]
                 [compojure "1.6.1"]
                 [ring/ring-jetty-adapter "1.7.1"]
                 [batik/batik-transcoder "1.6"]
                 [batik/batik-svg-dom "1.6"]
                 [batik/batik-dom "1.6"]
                 [batik/batik-bridge "1.6"]
                 [batik/batik-gvt "1.6"]
                 [batik/batik-util "1.6"]
                 [batik/batik-ext "1.6"]
                 [batik/batik-xml "1.6"]
                 [batik/batik-script "1.6"]
                 [batik/batik-awt-util "1.6"]
                 [batik/batik-parser "1.6"]
                 [batik/batik-css "1.6"]
                 [xerces/xerces "2.4.0"]])
